name: tests

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Execute Tests
      run: make tests
